### PR TITLE
MGO-131: Added whitespace trimming of keys in json decoder

### PR DESCRIPTION
**Pull request by tdelacour**
Jira: https://jira.mongodb.org/browse/MGO-131

QA done:
- Ran existing decode_test.go tests
- manually verified that change fixed the bug in question

### CODE REVIEW

**Review by craiggwilson — CHANGES_REQUESTED** [review]
More than passing existing tests and manual QA, we need an automated test to handle future regressions. I'd write a test that fails, then apply your change and watch the test pass. 

Tell me if this is right: at the point where you are trimming the whitespace, the name is everything from the last token ('{' or ',') up to the next token (':'). Hence, when unquote is getting run, any whitespace preceding or following the name when quoted causes the unquote to fail.

**Comment by tdelacour** [comment]
Yup, that's correct. In the example given in the ticket description, the code would have been running 
`unquote('"foo" ')` and would fail because `unquote` expects the first and last bytes to both be quotation marks.

I'll add a new automation test, thanks!

**Comment by tdelacour** [comment]
OK, the new test only passes after implementing the changes

**Review by craiggwilson — APPROVED** [review]
lgtm.

**Comment by tdelacour** [comment]
@craiggwilson thanks! Do you mind merging this in for me? I do not have write access to this repository.

**Comment by craiggwilson** [comment]
@jyemin Can you merge this? I don't have write access yet.

**Comment by jyemin** [comment]
@tdelacour please squash your commits and then I'll merge.

**Comment by tdelacour** [comment]
done :)

**Pull request merged**
