### PR TITLE
Add support for marshaling to/from mongo-go-driver/bson

### PR DESCRIPTION
**Pull request by xdg**

### CODE REVIEW

**Comment by xdg** [comment]
I added RawD.  Please let me know if I've missed anything.

**Comment by edaniels** [comment]
LGTM.

**Comment by skriptble** [comment]
FYI this is changing in a release soon.

**Comment by xdg** [comment]
@skriptble, that's OK.  Could you please open an MGO ticket when it ships and we'll fix this up.

**Pull request closed without merging**
